FROM debian:latest

RUN apt update && apt install -y python3 lame madplay ezstream

ADD run-ezstream.sh download_ahead.sh /
ADD playlist.py download_item.py log.py /
ADD playlist-program.sh /

CMD /run-ezstream.sh
